import React, { useState } from 'react';
import { HintStep, HintLevel } from '@/lib/types';
import {
  IconSparkles,
  IconArrowRight,
  IconCheck,
  IconCopy,
  IconLightbulb,
  IconCpu,
  IconStepDirection,
  IconStepDataStruct,
  IconStepInsight,
  IconStepImpl,
  IconStepSolution,
} from './Icons';

interface HintPanelProps {
  hints: HintStep[];
  currentLevel: HintLevel | 0;
  onNextHint: (customNote?: string) => void;
  onShowApproach: () => void;
  isLoading: boolean;
  hasInput: boolean;
}

export function HintPanel({
  hints,
  currentLevel,
  onNextHint,
  onShowApproach,
  isLoading,
  hasInput,
}: HintPanelProps) {
  const [customNote, setCustomNote] = useState('');
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);

  const handleCopy = (text: string, idx: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIdx(idx);
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  const handleNextClick = () => {
    onNextHint(customNote);
    setCustomNote('');
  };

  const activeHint = hints.length > 0 ? hints[hints.length - 1] : null;

  const stepperItems = [
    { level: 1, label: 'Direction', Icon: IconStepDirection },
    { level: 2, label: 'Data Struct', Icon: IconStepDataStruct },
    { level: 3, label: 'Insight', Icon: IconStepInsight },
    { level: 4, label: 'Impl', Icon: IconStepImpl },
    { level: 'approach', label: 'Approach', Icon: IconStepSolution },
  ];

  return (
    <div className="bg-white border border-slate-200/90 rounded-xl p-5 sm:p-6 shadow-2xs flex flex-col h-full min-h-[500px]">
      
      {/* Panel Header */}
      <div className="flex items-center justify-between border-b border-slate-100 pb-4 mb-4">
        <div className="flex items-center space-x-2.5">
          <div className="p-2 rounded-lg bg-blue-50 border border-blue-200/70 text-blue-700 shadow-2xs icon-glow-blue">
            <IconLightbulb className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 font-sans">
              AI Hint Tutor Panel
            </h2>
            <p className="text-[11px] text-slate-500 font-sans">
              Progressive guiding hints generated by Gemma-2-9B
            </p>
          </div>
        </div>

        {hints.length > 0 && (
          <span className="text-xs font-mono font-bold px-2.5 py-1 rounded-lg bg-slate-100 text-slate-800 border border-slate-200/80 shadow-2xs">
            {hints.length} / 5 Steps
          </span>
        )}
      </div>

      {/* Progressive Stepper Indicator */}
      <div className="grid grid-cols-5 gap-2 mb-6">
        {stepperItems.map((step, idx) => {
          const isDone = hints.some((h) => h.level === step.level);
          const isCurrent = activeHint?.level === step.level;
          const StepIcon = step.Icon;

          return (
            <div key={idx} className="flex flex-col items-center group cursor-default">
              <div
                className={`w-full h-2 rounded-full transition-all duration-300 ${
                  isCurrent
                    ? 'bg-blue-600 shadow-2xs'
                    : isDone
                    ? 'bg-blue-400'
                    : 'bg-slate-100'
                }`}
              />
              <div className="flex items-center space-x-1 mt-2">
                <StepIcon className={`w-3.5 h-3.5 transition-opacity ${isCurrent || isDone ? 'opacity-100' : 'opacity-40'}`} />
                <span
                  className={`text-[10px] font-sans font-semibold transition-colors ${
                    isCurrent
                      ? 'text-blue-900 font-bold'
                      : isDone
                      ? 'text-blue-700'
                      : 'text-slate-400'
                  }`}
                >
                  {step.label}
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Hints List / Display Area */}
      <div className="flex-1 overflow-y-auto space-y-4 pr-1">
        {hints.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center text-center p-6 border-2 border-dashed border-slate-200/90 rounded-xl my-2 bg-slate-50/40">
            <div className="w-12 h-12 rounded-xl bg-blue-50 border border-blue-200/60 flex items-center justify-center mb-3 shadow-2xs icon-glow-blue">
              <IconSparkles className="w-6 h-6" />
            </div>
            <h3 className="text-sm font-bold text-slate-800 mb-1 font-sans">
              Ready for Interactive Hints
            </h3>
            <p className="text-xs text-slate-500 max-w-xs leading-relaxed font-sans">
              Enter your DSA problem and current attempt on the left, then click <strong className="text-blue-600">"Get Hint"</strong>.
            </p>
            {!hasInput && (
              <p className="text-[11px] text-slate-500 font-mono mt-3 bg-white px-3 py-1 rounded-md border border-slate-200/60 shadow-2xs">
                💡 Tip: Click "Sample Demo" in header to test immediately.
              </p>
            )}
          </div>
        ) : (
          hints.map((hint, idx) => {
            const isLatest = idx === hints.length - 1;
            return (
              <div
                key={idx}
                className={`border rounded-xl p-4.5 transition-all duration-200 ${
                  isLatest
                    ? 'border-blue-200 bg-blue-50/30 shadow-2xs ring-1 ring-blue-500/10'
                    : 'border-slate-200/80 bg-white opacity-90'
                }`}
              >
                {/* Hint Step Header */}
                <div className="flex items-center justify-between border-b border-slate-100 pb-2.5 mb-3">
                  <div className="flex items-center space-x-2">
                    <span className="text-[10px] font-mono font-extrabold uppercase px-2.5 py-0.5 rounded-md bg-slate-900 text-white shadow-2xs">
                      {hint.level === 'approach' ? 'Full Solution' : `Hint ${hint.level}`}
                    </span>
                    <h3 className="text-xs font-bold text-slate-900 font-sans tracking-tight">
                      {hint.title}
                    </h3>
                  </div>

                  <div className="flex items-center space-x-2">
                    <button
                      onClick={() => handleCopy(hint.content, idx)}
                      className="text-slate-400 hover:text-slate-700 text-xs p-1.5 rounded-lg hover:bg-slate-100 transition-colors"
                      title="Copy hint text"
                    >
                      {copiedIdx === idx ? (
                        <IconCheck className="w-4 h-4 text-blue-600" />
                      ) : (
                        <IconCopy className="w-4 h-4" />
                      )}
                    </button>
                  </div>
                </div>

                {/* Hint Content Body */}
                <div className="markdown-body text-xs text-slate-700 leading-relaxed font-sans">
                  {renderMarkdown(hint.content)}
                </div>

                {/* Metadata footer indicating model */}
                <div className="mt-3.5 pt-2.5 border-t border-slate-100 flex items-center justify-between text-[10px] text-slate-400 font-mono">
                  <div className="flex items-center space-x-1.5">
                    <IconCpu className="w-3.5 h-3.5" />
                    <span>Powered by {hint.modelName || 'Gemma-2-9B'}</span>
                  </div>
                  <span>{hint.timestamp}</span>
                </div>
              </div>
            );
          })
        )}

        {/* Loading Indicator inside panel */}
        {isLoading && (
          <div className="border border-blue-100 bg-blue-50/40 rounded-xl p-4 animate-pulse space-y-2.5">
            <div className="flex items-center space-x-2">
              <div className="w-20 h-4 bg-blue-200/60 rounded-md"></div>
              <div className="w-36 h-4 bg-blue-100 rounded-md"></div>
            </div>
            <div className="w-full h-3 bg-blue-100/80 rounded-md"></div>
            <div className="w-4/5 h-3 bg-blue-100/60 rounded-md"></div>
            <div className="w-2/3 h-3 bg-blue-100/40 rounded-md"></div>
          </div>
        )}
      </div>

      {/* Action Footer Controls */}
      {hints.length > 0 && currentLevel !== 'approach' && (
        <div className="mt-4 pt-4 border-t border-slate-200/80 space-y-3">
          
          {/* Optional custom note / follow-up input */}
          <div className="space-y-1">
            <input
              type="text"
              value={customNote}
              onChange={(e) => setCustomNote(e.target.value)}
              placeholder="Ask a specific question for next hint (e.g. 'Why Two Pointers?')"
              className="w-full px-3.5 py-2 text-xs bg-slate-50 border border-slate-200/90 rounded-lg text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-600 font-sans shadow-2xs"
            />
          </div>

          <div className="grid grid-cols-2 gap-2.5">
            <button
              type="button"
              disabled={isLoading}
              onClick={handleNextClick}
              className="py-2.5 px-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-bold font-sans flex items-center justify-center space-x-2 transition-all shadow-2xs active:scale-[0.99]"
            >
              <span>Another Hint</span>
              <IconArrowRight className="w-4 h-4 text-white" />
            </button>

            <button
              type="button"
              disabled={isLoading}
              onClick={onShowApproach}
              className="py-2.5 px-3 bg-white border border-slate-300 hover:bg-blue-50/80 text-slate-800 rounded-lg text-xs font-bold font-sans flex items-center justify-center space-x-2 transition-all shadow-2xs active:scale-[0.99]"
            >
              <IconLightbulb className="w-4 h-4" />
              <span>Show Approach</span>
            </button>
          </div>
        </div>
      )}

      {/* Full Approach Completed State */}
      {currentLevel === 'approach' && (
        <div className="mt-4 pt-3 border-t border-slate-200 flex items-center justify-between text-xs text-slate-500 font-sans">
          <span className="font-bold text-blue-700 flex items-center">
            <IconCheck className="w-4 h-4 mr-1.5" />
            Full Optimal Solution Revealed
          </span>
          <button
            onClick={() => onNextHint('reset')}
            className="text-xs font-semibold text-blue-600 hover:text-blue-800 underline font-sans"
          >
            Start New Session
          </button>
        </div>
      )}

    </div>
  );
}

// Lightweight Markdown Renderer (handles code blocks, bold, headers, math notation safely)
function renderMarkdown(content: string) {
  if (!content) return null;

  const parts = content.split(/(```[\s\S]*?```)/g);

  return (
    <>
      {parts.map((part, index) => {
        if (part.startsWith('```')) {
          const match = part.match(/```(\w+)?\n?([\s\S]*?)```/);
          const lang = match ? match[1] || 'code' : 'text';
          const code = match ? match[2].trim() : part.replace(/```/g, '').trim();

          return (
            <div key={index} className="relative group my-2.5">
              <div className="absolute right-3 top-2.5 text-[10px] font-mono text-slate-400 uppercase bg-slate-800/90 px-2 py-0.5 rounded-md border border-slate-700">
                {lang}
              </div>
              <pre>
                <code>{code}</code>
              </pre>
            </div>
          );
        }

        const lines = part.split('\n');
        return (
          <div key={index}>
            {lines.map((line, lIdx) => {
              if (line.startsWith('### ')) {
                return <h3 key={lIdx}>{line.replace('### ', '')}</h3>;
              }
              if (line.startsWith('#### ')) {
                return <h4 key={lIdx}>{line.replace('#### ', '')}</h4>;
              }
              if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
                return (
                  <ul key={lIdx}>
                    <li>{formatBoldText(line.trim().substring(2))}</li>
                  </ul>
                );
              }
              if (line.trim() === '') return <div key={lIdx} className="h-1.5" />;

              return <p key={lIdx}>{formatBoldText(line)}</p>;
            })}
          </div>
        );
      })}
    </>
  );
}

function formatBoldText(text: string) {
  const parts = text.split(/(\*\*.*?\*\*|`.*?`)/g);

  return parts.map((part, idx) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={idx} className="font-extrabold text-slate-900">{part.slice(2, -2)}</strong>;
    }
    if (part.startsWith('`') && part.endsWith('`')) {
      return <code key={idx}>{part.slice(1, -1)}</code>;
    }
    return part;
  });
}
